In [4]:
import csv

def generate_insert_statements(csv_data: str):
    reader = csv.DictReader(csv_data.strip().splitlines())
    location_inserts = []
    id_counter = 1  # AUTO_INCREMENT를 흉내 내기 위해 사용 (실제 DB에선 생략)

    for row in reader:
        print(row)
        source_id = row["연번"]
        name = row["상호"]
        full_address = row["도로명주소"]
        lat = round(float(row["위도"]), 2)
        lng = round(float(row["경도"]), 2)

        # 주소에서 시(city)와 구(district) 분리
        parts = full_address.split()
        city = parts[0] if len(parts) > 0 else None
        district = parts[1] if len(parts) > 1 else None

        insert_sql = f"""INSERT INTO recycle_locations (address, city, district, latitude, longitude, name, source_id)
VALUES ('{full_address}', '{city}', '{district}', {lat}, {lng}, '{name}', '{source_id}');"""
        location_inserts.append(insert_sql)

        id_counter += 1  # 다음 레코드를 위한 ID 증가 (실제 INSERT에는 사용되지 않음)

    return "\n".join(location_inserts)
  
def generate_insert_medicine(csv_data: str):
    reader = csv.DictReader(csv_data.strip().splitlines())
    location_inserts = []
    id_counter = 1  # AUTO_INCREMENT를 흉내 내기 위해 사용 (실제 DB에선 생략)

    for row in reader:
        print(row)
        full_address = row["도로명 주소"]
        city = full_address.split()[0] if len(full_address.split()) > 0 else None
        district = full_address.split()[1] if len(full_address.split()) > 1 else None
        name = row["관리번호"]
        lat = round(float(row["위도"]), 2)
        lng = round(float(row["경도"]), 2)
        source_id = row["연번"]

        insert_sql = f"""INSERT INTO recycle_locations (address, city, district, latitude, longitude, name, source_id)
VALUES ('{full_address}', '{city}', '{district}', {lat}, {lng}, '{name}', '{source_id}');"""
        location_inserts.append(insert_sql)

        id_counter += 1  # 다음 레코드를 위한 ID 증가 (실제 INSERT에는 사용되지 않음)

    return "\n".join(location_inserts)



# 예시 CSV 데이터

# with open('yeonsu_medicine.csv', mode='r', encoding='utf-8') as f:
#   csv_data = f.read()
#   # SQL 생성
#   sql_output = generate_insert_statements(csv_data)
#   print(sql_output)
  
with open('yeonsu_clothing.csv', mode='r', encoding='utf-8') as f:
  csv_data = f.read()
  print(generate_insert_medicine(csv_data))

{'연번': '1', '관리번호': '선학-1', '도로명 주소': '인천광역시 연수구 비류대로529번길 3', '위도': '37.423238', '경도': '126.6932665'}
{'연번': '2', '관리번호': '선학-2', '도로명 주소': '인천광역시 연수구 비류대로519번길 3-2', '위도': '37.4232237', '경도': '126.6922219'}
{'연번': '3', '관리번호': '선학-3', '도로명 주소': '인천광역시 연수구 비류대로519번길 3-8', '위도': '37.423217', '경도': '126.6918734'}
{'연번': '4', '관리번호': '선학-4', '도로명 주소': '인천광역시 연수구 비류대로519번길 3-32', '위도': '37.4237629', '경도': '126.6921303'}
{'연번': '5', '관리번호': '선학-5', '도로명 주소': '인천광역시 연수구 비류대로519번길 32', '위도': '37.4243917', '경도': '126.6921171'}
{'연번': '6', '관리번호': '선학-6', '도로명 주소': '인천광역시 연수구 비류대로529번길 51', '위도': '37.4247821', '경도': '126.6922194'}
{'연번': '7', '관리번호': '선학-7', '도로명 주소': '인천광역시 연수구 비류대로529번길 23', '위도': '37.4244389', '경도': '126.6933292'}
{'연번': '8', '관리번호': '선학-8', '도로명 주소': '인천광역시 연수구 비류대로529번길 22-23', '위도': '37.4243043', '경도': '126.6948283'}
{'연번': '9', '관리번호': '선학-9', '도로명 주소': '인천광역시 연수구 비류대로541번길 14-2', '위도': '37.4239375', '경도': '126.6948112'}
{'연번': '10', '관리번호': '선학-10', '도로명 주소': '인천광역시 연수구 비류대로541번길 14-14', '위도': '37.4239882', '경도': '126.6955141'}
{'연번': '11', '관리번호': '선학-11', '도로명 주소': '인천광역시 연수구 비류대로541번길 6', '위도': '37.4234687', '경도': '126.6948009'}
{'연번': '12', '관리번호': '선학-12', '도로명 주소': '인천광역시 연수구 학나래로45번길 27', '위도': '37.4245155', '경도': '126.6957769'}
{'연번': '13', '관리번호': '선학-13', '도로명 주소': '인천광역시 연수구 학나래로45번길 3', '위도': '37.4253846', '경도': '126.6962847'}
{'연번': '14', '관리번호': '선학-14', '도로명 주소': '인천광역시 연수구 학나래로 40', '위도': '37.4254182', '경도': '126.6966457'}
{'연번': '15', '관리번호': '선학-15', '도로명 주소': '인천광역시 연수구 학나래로 34', '위도': '37.4251001', '경도': '126.6965554'}
{'연번': '16', '관리번호': '선학-16', '도로명 주소': '인천광역시 연수구 학나래로 23', '위도': '37.4244269', '경도': '126.6966439'}
{'연번': '17', '관리번호': '선학-17', '도로명 주소': '인천광역시 연수구 학나래로14번길 8', '위도': '37.4240627', '경도': '126.6969592'}
{'연번': '18', '관리번호': '선학-18', '도로명 주소': '인천광역시 연수구 학나래로46번길 20', '위도': '37.4253414', '경도': '126.6974805'}
{'연번': '19', '관리번호': '선학-19', '도로명 주소': '인천광역시 연수구 학나래로22번길 23', '위도': '37.4252555', '경도': '126.6970566'}
{'연번': '20', '관리번호': '선학-20', '도로명 주소': '인천광역시 연수구 학나래로22번길 15', '위도': '37.4249545', '경도': '126.6970197'}
{'연번': '21', '관리번호': '선학-21', '도로명 주소': '인천광역시 연수구 학나래로 79', '위도': '37.4267965', '경도': '126.6969738'}
{'연번': '22', '관리번호': '선학-22', '도로명 주소': '인천광역시 연수구 학나래로117번길 3', '위도': '37.4282403', '경도': '126.6980483'}
{'연번': '23', '관리번호': '선학-23', '도로명 주소': '인천광역시 연수구 경원대로483번길 15-7', '위도': '37.4271044', '경도': '126.6975771'}
{'연번': '24', '관리번호': '선학-24', '도로명 주소': '인천광역시 연수구 경원대로467번길 26-11', '위도': '37.4262558', '경도': '126.6975032'}
{'연번': '25', '관리번호': '선학-25', '도로명 주소': '인천광역시 연수구 경원대로467번길 26-1', '위도': '37.4262641', '경도': '126.6971721'}
{'연번': '26', '관리번호': '선학-26', '도로명 주소': '인천광역시 연수구 학나래로117번길 14', '위도': '37.4289694', '경도': '126.6977824'}
{'연번': '27', '관리번호': '선학-27', '도로명 주소': '인천광역시 연수구 넘말로 31', '위도': '37.4292941', '경도': '126.697334'}
{'연번': '28', '관리번호': '선학-28', '도로명 주소': '인천광역시 연수구 넘말로 48', '위도': '37.4299465', '경도': '126.696802'}
{'연번': '29', '관리번호': '선학-29', '도로명 주소': '인천광역시 연수구 넘말로 69', '위도': '37.4310112', '경도': '126.6969016'}
{'연번': '30', '관리번호': '선학-30', '도로명 주소': '인천광역시 연수구 넘말로79번길 55-1', '위도': '37.4293897', '경도': '126.6947877'}
{'연번': '31', '관리번호': '선학-31', '도로명 주소': '인천광역시 연수구 넘말로79번길 55-11', '위도': '37.4290731', '경도': '126.6953278'}
{'연번': '32', '관리번호': '선학-32', '도로명 주소': '인천광역시 연수구 넘말로47번길 31', '위도': '37.4288303', '경도': '126.6956881'}
{'연번': '33', '관리번호': '선학-33', '도로명 주소': '인천광역시 연수구 넘말로47번길 20', '위도': '37.4293105', '경도': '126.6962782'}
{'연번': '34', '관리번호': '선학-34', '도로명 주소': '인천광역시 연수구 넘말로55번길 19', '위도': '37.4297376', '경도': '126.6959813'}
{'연번': '35', '관리번호': '선학-35', '도로명 주소': '인천광역시 연수구 넘말로55번길 4', '위도': '37.4302486', '경도': '126.6965603'}
{'연번': '36', '관리번호': '선학-36', '도로명 주소': '인천광역시 연수구 넘말로29번길 36', '위도': '37.4282736', '경도': '126.6957292'}
{'연번': '37', '관리번호': '선학-37', '도로명 주소': '인천광역시 연수구 넘말로29번길 20', '위도': '37.4286959', '경도': '126.696645'}
{'연번': '38', '관리번호': '선학-38', '도로명 주소': '인천광역시 연수구 학나래로117번길 19', '위도': '37.4289794', '경도': '126.6971858'}
{'연번': '39', '관리번호': '선학-39', '도로명 주소': '인천광역시 연수구 학나래로117번길 14', '위도': '37.4287476', '경도': '126.6975606'}
{'연번': '40', '관리번호': '선학-40', '도로명 주소': '인천광역시 연수구 경원대로483번길 30', '위도': '37.4278905', '경도': '126.697127'}
{'연번': '41', '관리번호': '선학-41', '도로명 주소': '인천광역시 연수구 경원대로483번길 40', '위도': '37.428129', '경도': '126.6967554'}
{'연번': '42', '관리번호': '선학-42', '도로명 주소': '인천광역시 연수구 경원대로588번길 13', '위도': '37.4362678', '경도': '126.6973429'}
{'연번': '43', '관리번호': '선학-43', '도로명 주소': '인천광역시 연수구 예술로22번길 20', '위도': '37.4360136', '경도': '126.6993347'}
{'연번': '44', '관리번호': '선학-44', '도로명 주소': '인천광역시 연수구 예술로22번길 42-1', '위도': '37.4360244', '경도': '126.7008124'}
{'연번': '45', '관리번호': '선학-45', '도로명 주소': '인천광역시 연수구 예술로22번길 54', '위도': '37.4359365', '경도': '126.7013092'}
{'연번': '46', '관리번호': '선학-46', '도로명 주소': '인천광역시 연수구 예술로22번길 68', '위도': '37.4358539', '경도': '126.7018836'}
{'연번': '47', '관리번호': '선학-47', '도로명 주소': '인천광역시 연수구 예술로20번길 75', '위도': '37.4347721', '경도': '126.7025559'}
{'연번': '48', '관리번호': '선학-48', '도로명 주소': '인천광역시 연수구 예술로20번길 26', '위도': '37.4354835', '경도': '126.7000791'}
{'연번': '49', '관리번호': '선학-49', '도로명 주소': '인천광역시 연수구 선학로68번길 8', '위도': '37.4235748', '경도': '126.701538'}
{'연번': '50', '관리번호': '선학-50', '도로명 주소': '인천광역시 연수구 선학로 54', '위도': '37.4224407', '경도': '126.7011771'}
{'연번': '51', '관리번호': '연수1-1', '도로명 주소': '인천광역시 연수구 비류대로331번길 5', '위도': '37.4252857', '경도': '126.6714364'}
{'연번': '52', '관리번호': '연수1-2', '도로명 주소': '인천광역시 연수구 비류대로347번길 5', '위도': '37.4251626', '경도': '126.6731648'}
{'연번': '53', '관리번호': '연수1-3', '도로명 주소': '인천광역시 연수구 함박로91번길 20', '위도': '37.4239196', '경도': '126.6873233'}
{'연번': '54', '관리번호': '연수1-4', '도로명 주소': '인천광역시 연수구 함박로91번길 4', '위도': '37.4240701', '경도': '126.6861518'}
{'연번': '55', '관리번호': '연수1-5', '도로명 주소': '인천광역시 연수구 함박로88번길 3', '위도': '37.4245734', '경도': '126.6860915'}
{'연번': '56', '관리번호': '연수1-6', '도로명 주소': '인천광역시 연수구 함박로 80', '위도': '37.4252981', '경도': '126.6860806'}
{'연번': '57', '관리번호': '연수1-7', '도로명 주소': '인천광역시 연수구 함박로67번길 4', '위도': '37.4254832', '경도': '126.6849982'}
{'연번': '58', '관리번호': '연수1-8', '도로명 주소': '인천광역시 연수구 함박로 58', '위도': '37.4255042', '경도': '126.6836991'}
{'연번': '59', '관리번호': '연수1-9', '도로명 주소': '인천광역시 연수구 함박안로62번길 88', '위도': '37.4259421', '경도': '126.6837783'}
{'연번': '60', '관리번호': '연수1-10', '도로명 주소': '인천광역시 연수구 함박안로62번길 96', '위도': '37.4258978', '경도': '126.6842596'}
{'연번': '61', '관리번호': '연수1-11', '도로명 주소': '인천광역시 연수구 함박안로156번길 15', '위도': '37.4262968', '경도': '126.6836464'}
{'연번': '62', '관리번호': '연수1-12', '도로명 주소': '인천광역시 연수구 함박안로134번길 15-1', '위도': '37.4262878', '경도': '126.6824891'}
{'연번': '63', '관리번호': '연수1-13', '도로명 주소': '인천광역시 연수구 함박안로62번길 54', '위도': '37.4261012', '경도': '126.6818239'}
{'연번': '64', '관리번호': '연수1-14', '도로명 주소': '인천광역시 연수구 비류대로 437', '위도': '37.424204', '경도': '126.6832524'}
{'연번': '65', '관리번호': '연수1-15', '도로명 주소': '인천광역시 연수구 비류대로 429', '위도': '37.4242654', '경도': '126.6822399'}
{'연번': '66', '관리번호': '연수1-16', '도로명 주소': '인천광역시 연수구 함박로4번길 24', '위도': '37.4245669', '경도': '126.6799347'}
{'연번': '67', '관리번호': '연수1-17', '도로명 주소': '인천광역시 연수구 함박로4번길 4', '위도': '37.4246921', '경도': '126.6787052'}
{'연번': '68', '관리번호': '연수1-18', '도로명 주소': '인천광역시 연수구 함박로3번길 3', '위도': '37.4246121', '경도': '126.6785553'}
{'연번': '69', '관리번호': '연수1-19', '도로명 주소': '인천광역시 연수구 함박안로 14', '위도': '37.4251561', '경도': '126.6767695'}
{'연번': '70', '관리번호': '연수1-20', '도로명 주소': '인천광역시 연수구 함박안로26번길 9', '위도': '37.425693', '경도': '126.6775492'}
{'연번': '71', '관리번호': '연수1-21', '도로명 주소': '인천광역시 연수구 함박안로 50', '위도': '37.4261311', '경도': '126.6781351'}
{'연번': '72', '관리번호': '연수1-22', '도로명 주소': '인천광역시 연수구 함박안로 68', '위도': '37.426391', '경도': '126.6788573'}
{'연번': '73', '관리번호': '연수1-23', '도로명 주소': '인천광역시 연수구 함박안로 72', '위도': '37.4266137', '경도': '126.6792243'}
{'연번': '74', '관리번호': '연수1-24', '도로명 주소': '인천광역시 연수구 함박로25번길 23', '위도': '37.4270484', '경도': '126.6800172'}
{'연번': '75', '관리번호': '연수1-25', '도로명 주소': '인천광역시 연수구 함박안로 136', '위도': '37.4271454', '경도': '126.6826203'}
{'연번': '76', '관리번호': '연수1-26', '도로명 주소': '인천광역시 연수구 함박안로 154', '위도': '37.4271504', '경도': '126.6838167'}
{'연번': '77', '관리번호': '연수1-27', '도로명 주소': '인천광역시 연수구 함박안로 200', '위도': '37.4261552', '경도': '126.6860465'}
{'연번': '78', '관리번호': '연수1-28', '도로명 주소': '인천광역시 연수구 함박로 79-9', '위도': '37.4259611', '경도': '126.6865675'}
{'연번': '79', '관리번호': '연수1-29', '도로명 주소': '인천광역시 연수구 함박안로 238', '위도': '37.4249652', '경도': '126.6876009'}
{'연번': '80', '관리번호': '연수1-30', '도로명 주소': '인천광역시 연수구 함박로92번길 24', '위도': '37.4244693', '경도': '126.684792'}
{'연번': '81', '관리번호': '연수1-31', '도로명 주소': '인천광역시 연수구 함박로67번길 18', '위도': '37.4262534', '경도': '126.6849673'}
{'연번': '82', '관리번호': '연수1-32', '도로명 주소': '인천광역시 연수구 먼우금로264번길 8-4', '위도': '37.4200767', '경도': '126.6802735'}
{'연번': '83', '관리번호': '연수1-33', '도로명 주소': '인천광역시 연수구 먼우금로264번길 18', '위도': '37.4195374', '경도': '126.6811944'}
{'연번': '84', '관리번호': '연수1-34', '도로명 주소': '인천광역시 연수구 새말로 107', '위도': '37.4186026', '경도': '126.6814081'}
{'연번': '85', '관리번호': '연수1-35', '도로명 주소': '인천광역시 연수구 새말로99번길 1', '위도': '37.4184937', '경도': '126.6804347'}
{'연번': '86', '관리번호': '연수1-36', '도로명 주소': '인천광역시 연수구 먼우금로252번길 1', '위도': '37.4192859', '경도': '126.6795205'}
{'연번': '87', '관리번호': '연수1-37', '도로명 주소': '인천광역시 연수구 새말로96번길 22', '위도': '37.4179924', '경도': '126.6794543'}
{'연번': '88', '관리번호': '연수1-38', '도로명 주소': '인천광역시 연수구 함박뫼로50번길 89', '위도': '37.4190295', '경도': '126.6776874'}
{'연번': '89', '관리번호': '연수1-39', '도로명 주소': '인천광역시 연수구 함박뫼로50번길 75', '위도': '37.4193289', '경도': '126.6770721'}
{'연번': '90', '관리번호': '연수1-40', '도로명 주소': '인천광역시 연수구 함박뫼로50번길 49', '위도': '37.4199707', '경도': '126.6757453'}
{'연번': '91', '관리번호': '연수1-41', '도로명 주소': '인천광역시 연수구 함박뫼로50번길 43', '위도': '37.420228', '경도': '126.6753233'}
{'연번': '92', '관리번호': '연수1-42', '도로명 주소': '인천광역시 연수구 새말로46번길 21', '위도': '37.4205672', '경도': '126.6747287'}
{'연번': '93', '관리번호': '연수1-43', '도로명 주소': '인천광역시 연수구 함박뫼로50번길 21-1', '위도': '37.4207476', '경도': '126.6744316'}
{'연번': '94', '관리번호': '연수1-44', '도로명 주소': '인천광역시 연수구 함박뫼로50번길 13', '위도': '37.4209208', '경도': '126.6741361'}
{'연번': '95', '관리번호': '연수1-45', '도로명 주소': '인천광역시 연수구 함박뫼로 52', '위도': '37.421394', '경도': '126.6734996'}
{'연번': '96', '관리번호': '연수1-46', '도로명 주소': '인천광역시 연수구 함박뫼로50번길 21-9', '위도': '37.4211381', '경도': '126.6749637'}
{'연번': '97', '관리번호': '연수1-47', '도로명 주소': '인천광역시 연수구 새말로56번길 3', '위도': '37.4206821', '경도': '126.6764571'}
{'연번': '98', '관리번호': '연수1-48', '도로명 주소': '인천광역시 연수구 새말로 68', '위도': '37.4198332', '경도': '126.6774952'}
{'연번': '99', '관리번호': '연수1-49', '도로명 주소': '인천광역시 연수구 새말로 70', '위도': '37.4196425', '경도': '126.67772'}
{'연번': '100', '관리번호': '연수1-50', '도로명 주소': '인천광역시 연수구 새말로 78', '위도': '37.4192872', '경도': '126.6784243'}
{'연번': '101', '관리번호': '연수1-51', '도로명 주소': '인천광역시 연수구 새말로 82', '위도': '37.4190615', '경도': '126.6788257'}
{'연번': '102', '관리번호': '연수1-52', '도로명 주소': '인천광역시 연수구 새말로69번길 25', '위도': '37.4209843', '경도': '126.6786292'}
{'연번': '103', '관리번호': '연수1-53', '도로명 주소': '인천광역시 연수구 새말로55번길 32', '위도': '37.4211651', '경도': '126.6780736'}
{'연번': '104', '관리번호': '연수1-54', '도로명 주소': '인천광역시 연수구 새말로55번길 26', '위도': '37.4211964', '경도': '126.6777603'}
{'연번': '105', '관리번호': '연수1-55', '도로명 주소': '인천광역시 연수구 함박뫼로84번길 32', '위도': '37.4219369', '경도': '126.6769938'}
{'연번': '106', '관리번호': '연수1-56', '도로명 주소': '인천광역시 연수구 함박뫼로84번길 16', '위도': '37.4224627', '경도': '126.6765008'}
{'연번': '107', '관리번호': '연수1-57', '도로명 주소': '인천광역시 연수구 새말로35번길 5', '위도': '37.4223757', '경도': '126.6754694'}
{'연번': '108', '관리번호': '연수1-58', '도로명 주소': '인천광역시 연수구 새말로45번길 17', '위도': '37.4219144', '경도': '126.6764756'}
{'연번': '109', '관리번호': '연수1-59', '도로명 주소': '인천광역시 연수구 새말로45번길 8-12', '위도': '37.4211407', '경도': '126.6766303'}
{'연번': '110', '관리번호': '연수1-60', '도로명 주소': '인천광역시 연수구 먼우금로251번길 13', '위도': '37.4197372', '경도': '126.678653'}
{'연번': '111', '관리번호': '연수1-61', '도로명 주소': '인천광역시 연수구 새말로69번길 16-15', '위도': '37.4199484', '경도': '126.6788337'}
{'연번': '112', '관리번호': '연수1-62', '도로명 주소': '인천광역시 연수구 새말로69번길 16-9', '위도': '37.4202028', '경도': '126.6784186'}
{'연번': '113', '관리번호': '연수1-63', '도로명 주소': '인천광역시 연수구 새말로69번길 9', '위도': '37.4201417', '경도': '126.6779567'}
{'연번': '114', '관리번호': '연수1-64', '도로명 주소': '인천광역시 연수구 함박로 16', '위도': '37.4258372', '경도': '126.6788412'}
{'연번': '115', '관리번호': '연수1-65', '도로명 주소': '인천광역시 연수구 함박로 12', '위도': '37.425608', '경도': '126.6788025'}
{'연번': '116', '관리번호': '연수1-66', '도로명 주소': '인천광역시 연수구 함박뫼로 127', '위도': '37.4221319', '경도': '126.6814281'}
{'연번': '117', '관리번호': '연수2-1', '도로명 주소': '인천광역시 연수구 용담로 147', '위도': '37.4129809', '경도': '126.6805726'}
{'연번': '118', '관리번호': '연수2-2', '도로명 주소': '인천광역시 연수구 용담로149번길 51', '위도': '37.4147113', '경도': '126.6824439'}
{'연번': '119', '관리번호': '연수2-3', '도로명 주소': '인천광역시 연수구 용담로125번길 54', '위도': '37.4162572', '경도': '126.6805422'}
{'연번': '120', '관리번호': '연수2-4', '도로명 주소': '인천광역시 연수구 벚꽃로 150', '위도': '37.4155837', '경도': '126.6817553'}
{'연번': '121', '관리번호': '연수2-5', '도로명 주소': '인천광역시 연수구 샘말로88번길 5', '위도': '37.414594', '경도': '126.6810565'}
{'연번': '122', '관리번호': '연수2-6', '도로명 주소': '인천광역시 연수구 샘말로88번길 5', '위도': '37.4147365', '경도': '126.6808163'}
{'연번': '123', '관리번호': '연수2-7', '도로명 주소': '인천광역시 연수구 샘말로 68-2', '위도': '37.4141744', '경도': '126.6802427'}
{'연번': '124', '관리번호': '연수2-8', '도로명 주소': '인천광역시 연수구 용담로 115', '위도': '37.4147403', '경도': '126.6779979'}
{'연번': '125', '관리번호': '연수2-9', '도로명 주소': '인천광역시 연수구 용담로117번길 41', '위도': '37.416557', '경도': '126.6787409'}
{'연번': '126', '관리번호': '연수2-10', '도로명 주소': '인천광역시 연수구 먼우금로222번길 37', '위도': '37.4159007', '경도': '126.6793008'}
{'연번': '127', '관리번호': '연수2-11', '도로명 주소': '인천광역시 연수구 용담로125번길 28', '위도': '37.4154055', '경도': '126.6796448'}
{'연번': '128', '관리번호': '연수2-12', '도로명 주소': '인천광역시 연수구 용담로125번길 12', '위도': '37.4146926', '경도': '126.678892'}
{'연번': '129', '관리번호': '연수2-13', '도로명 주소': '인천광역시 연수구 청능대로137번길 47', '위도': '37.4127543', '경도': '126.6803312'}
{'연번': '130', '관리번호': '연수2-14', '도로명 주소': '인천광역시 연수구 샘말로30번길 20', '위도': '37.4121021', '경도': '126.6796617'}
{'연번': '131', '관리번호': '연수2-15', '도로명 주소': '인천광역시 연수구 샘말로 37-4', '위도': '37.413048', '경도': '126.6788447'}
{'연번': '132', '관리번호': '연수2-16', '도로명 주소': '인천광역시 연수구 샘말로21번길 14-11', '위도': '37.4133535', '경도': '126.6782072'}
{'연번': '133', '관리번호': '연수2-17', '도로명 주소': '인천광역시 연수구 샘말로21번길 14-3', '위도': '37.4130927', '경도': '126.6779449'}
{'연번': '134', '관리번호': '연수2-18', '도로명 주소': '인천광역시 연수구 먼우금로 194', '위도': '37.4144375', '경도': '126.6771797'}
{'연번': '135', '관리번호': '연수2-19', '도로명 주소': '인천광역시 연수구 원인재로 158', '위도': '37.4117446', '경도': '126.6817011'}
{'연번': '136', '관리번호': '청학-1', '도로명 주소': '인천광역시 연수구 용담로63번길 26', '위도': '37.41944', '경도': '126.6752'}
{'연번': '137', '관리번호': '청학-2', '도로명 주소': '인천광역시 연수구 청명로 34', '위도': '37.41835', '경도': '126.6763'}
{'연번': '138', '관리번호': '청학-3', '도로명 주소': '인천광역시 연수구 청명로 15', '위도': '37.4172', '경도': '126.6751'}
{'연번': '139', '관리번호': '청학-4', '도로명 주소': '인천광역시 연수구 용담로 67-1', '위도': '37.41812', '경도': '126.6744'}
{'연번': '140', '관리번호': '청학-5', '도로명 주소': '인천광역시 연수구 청명로17번길 30', '위도': '37.41878', '경도': '126.6746'}
{'연번': '141', '관리번호': '청학-6', '도로명 주소': '인천광역시 연수구 용담로50번길 1', '위도': '37.41923', '경도': '126.6731'}
{'연번': '142', '관리번호': '청학-7', '도로명 주소': '인천광역시 연수구 함박뫼로12번길 24', '위도': '37.41828', '경도': '126.6726'}
{'연번': '143', '관리번호': '청학-8', '도로명 주소': '인천광역시 연수구 함박뫼로12번길 24', '위도': '37.41828', '경도': '126.6726'}
{'연번': '144', '관리번호': '청학-9', '도로명 주소': '인천광역시 연수구 함박뫼로12번길 1', '위도': '37.41852', '경도': '126.6715'}
{'연번': '145', '관리번호': '청학-10', '도로명 주소': '인천광역시 연수구 함박뫼로26번길 2', '위도': '37.4197', '경도': '126.6718'}
{'연번': '146', '관리번호': '청학-11', '도로명 주소': '인천광역시 연수구 함박뫼로 28', '위도': '37.41993', '경도': '126.6722'}
{'연번': '147', '관리번호': '청학-12', '도로명 주소': '인천광역시 연수구 청능대로53번길 32', '위도': '37.41824', '경도': '126.6742'}
{'연번': '148', '관리번호': '청학-13', '도로명 주소': '인천광역시 연수구 청명로 9', '위도': '37.41674', '경도': '126.6747'}
{'연번': '149', '관리번호': '청학-14', '도로명 주소': '인천광역시 연수구 청명로 5', '위도': '37.41639', '경도': '126.6742'}
{'연번': '150', '관리번호': '청학-15', '도로명 주소': '인천광역시 연수구 청능대로55번길 3', '위도': '37.41679', '경도': '126.673'}
{'연번': '151', '관리번호': '청학-16', '도로명 주소': '인천광역시 연수구 청능대로53번길 6', '위도': '37.41701', '경도': '126.6727'}
{'연번': '152', '관리번호': '청학-17', '도로명 주소': '인천광역시 연수구 함박뫼로4번길 22', '위도': '37.41727', '경도': '126.6722'}
{'연번': '153', '관리번호': '청학-18', '도로명 주소': '인천광역시 연수구 함박뫼로4번길 1', '위도': '37.41758', '경도': '126.671'}
{'연번': '154', '관리번호': '청학-19', '도로명 주소': '인천광역시 연수구 청능말로7번길 19', '위도': '37.41737', '경도': '126.6697'}
{'연번': '155', '관리번호': '청학-20', '도로명 주소': '인천광역시 연수구 청능말로22번길 6', '위도': '37.41686', '경도': '126.668'}
{'연번': '156', '관리번호': '청학-21', '도로명 주소': '인천광역시 연수구 청능말로22번길 24', '위도': '37.41714', '경도': '126.667'}
{'연번': '157', '관리번호': '청학-22', '도로명 주소': '인천광역시 연수구 청능말로8번길 21', '위도': '37.41769', '경도': '126.6671'}
{'연번': '158', '관리번호': '청학-23', '도로명 주소': '인천광역시 연수구 청능말로 13-4', '위도': '37.41724', '경도': '126.6683'}
{'연번': '159', '관리번호': '청학-24', '도로명 주소': '인천광역시 연수구 솔샘로73번길 17', '위도': '37.42433', '경도': '126.6649'}
{'연번': '160', '관리번호': '청학-25', '도로명 주소': '인천광역시 연수구 솔샘로 56', '위도': '37.42461', '경도': '126.6654'}
{'연번': '161', '관리번호': '청학-26', '도로명 주소': '인천광역시 연수구 솔샘로 66', '위도': '37.42475', '경도': '126.6651'}
{'연번': '162', '관리번호': '청학-27', '도로명 주소': '인천광역시 연수구 솔샘로 78', '위도': '37.42497', '경도': '126.6646'}
{'연번': '163', '관리번호': '청학-28', '도로명 주소': '인천광역시 연수구 솔샘로 85', '위도': '37.42517', '경도': '126.6641'}
{'연번': '164', '관리번호': '청학-29', '도로명 주소': '인천광역시 연수구 솔샘로 90', '위도': '37.42536', '경도': '126.6638'}
{'연번': '165', '관리번호': '청학-30', '도로명 주소': '인천광역시 연수구 솔샘로 95', '위도': '37.42544', '경도': '126.6633'}
{'연번': '166', '관리번호': '청학-31', '도로명 주소': '인천광역시 연수구 솔샘로 106', '위도': '37.42563', '경도': '126.6628'}
{'연번': '167', '관리번호': '청학-32', '도로명 주소': '인천광역시 연수구 솔샘로134번길 13', '위도': '37.4259', '경도': '126.6614'}
{'연번': '168', '관리번호': '청학-33', '도로명 주소': '인천광역시 연수구 솔샘로 143', '위도': '37.42534', '경도': '126.6607'}
{'연번': '169', '관리번호': '청학-34', '도로명 주소': '인천광역시 연수구 비류대로232번길 60', '위도': '37.42428', '경도': '126.6608'}
{'연번': '170', '관리번호': '청학-35', '도로명 주소': '인천광역시 연수구 비류대로256번길 22', '위도': '37.42586', '경도': '126.6632'}
{'연번': '171', '관리번호': '청학-36', '도로명 주소': '인천광역시 연수구 비류대로278번길 18-24', '위도': '37.42609', '경도': '126.6638'}
{'연번': '172', '관리번호': '청학-37', '도로명 주소': '인천광역시 연수구 비류대로278번길 28-10', '위도': '37.42557', '경도': '126.6642'}
{'연번': '173', '관리번호': '청학-38', '도로명 주소': '인천광역시 연수구 비류대로294번길 32-24', '위도': '37.42515', '경도': '126.6653'}
{'연번': '174', '관리번호': '청학-39', '도로명 주소': '인천광역시 연수구 비류대로294번길 32-14', '위도': '37.42489', '경도': '126.6658'}
{'연번': '175', '관리번호': '청학-40', '도로명 주소': '인천광역시 연수구 비류대로294번길 6-28', '위도': '37.42573', '경도': '126.6667'}
{'연번': '176', '관리번호': '청학-41', '도로명 주소': '인천광역시 연수구 비류대로278번길 16', '위도': '37.42572', '경도': '126.6652'}
{'연번': '177', '관리번호': '청학-42', '도로명 주소': '인천광역시 연수구 비류대로278번길 4', '위도': '37.42621', '경도': '126.6651'}
{'연번': '178', '관리번호': '청학-43', '도로명 주소': '인천광역시 연수구 비류대로278번길 8-11', '위도': '37.42625', '경도': '126.6647'}
{'연번': '179', '관리번호': '청학-44', '도로명 주소': '인천광역시 연수구 미추홀대로304번길 10', '위도': '37.42585', '경도': '126.6706'}
{'연번': '180', '관리번호': '청학-45', '도로명 주소': '인천광역시 연수구 청학로6번길 78', '위도': '37.42673', '경도': '126.6676'}
{'연번': '181', '관리번호': '청학-46', '도로명 주소': '인천광역시 연수구 비류대로303번길 10', '위도': '37.42641', '경도': '126.6686'}
{'연번': '182', '관리번호': '청학-47', '도로명 주소': '인천광역시 연수구 계림로112번길 31', '위도': '37.42628', '경도': '126.669'}
{'연번': '183', '관리번호': '청학-48', '도로명 주소': '인천광역시 연수구 계림로112번길 25', '위도': '37.42664', '경도': '126.6692'}
{'연번': '184', '관리번호': '청학-49', '도로명 주소': '인천광역시 연수구 비류대로303번길 39', '위도': '37.4276', '경도': '126.669'}
{'연번': '185', '관리번호': '청학-50', '도로명 주소': '인천광역시 연수구 비류대로303번길 28', '위도': '37.42699', '경도': '126.6687'}
{'연번': '186', '관리번호': '청학-51', '도로명 주소': '인천광역시 연수구 청학로16번길 82', '위도': '37.42752', '경도': '126.6683'}
{'연번': '187', '관리번호': '청학-52', '도로명 주소': '인천광역시 연수구 청학로16번길 98', '위도': '37.4274', '경도': '126.6688'}
{'연번': '188', '관리번호': '청학-53', '도로명 주소': '인천광역시 연수구 계림로 79-8', '위도': '37.4286', '경도': '126.6682'}
{'연번': '189', '관리번호': '청학-54', '도로명 주소': '인천광역시 연수구 계림로91번길 13', '위도': '37.42841', '경도': '126.6689'}
{'연번': '190', '관리번호': '청학-55', '도로명 주소': '인천광역시 연수구 계림로91번길 17', '위도': '37.42877', '경도': '126.669'}
{'연번': '191', '관리번호': '청학-56', '도로명 주소': '인천광역시 연수구 계림로57번길 59', '위도': '37.42947', '경도': '126.6695'}
{'연번': '192', '관리번호': '청학-57', '도로명 주소': '인천광역시 연수구 계림로57번길 28', '위도': '37.42915', '경도': '126.6677'}